# Generated by Django 4.2.4 on 2023-09-01 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bio_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('Genda', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=50)),
                ('Town', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Phone_Number1', models.IntegerField(max_length=50)),
                ('Phone_Number2', models.IntegerField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tech.customerdetail')),
            ],
        ),
    ]
